### ISSUE TITLE
Web demo provides different labels

### ISSUE THREAD

**Issue by GoncaloBFM** [GKalliatakis/Keras-VGG16-places365#7] opened 2018-04-10 15:42 UTC
I'm using the provided sample code for the places365 model but I seem to be having different results from those provided by the demo in http://places2.csail.mit.edu/demo.html

Namely for the image present in the repository, restaurant.jpg I get the labels _food_court_  and _cafeteria_ while using the demo and I get the following labels: _museum/indoor coffee_shop art_studio campus inn/outdoor_ when using the sample code.

**Comment by GKalliatakis** [comment] 2018-04-24 07:54
Duplicate of #5

**Closed as completed by GKalliatakis** 2018-04-24 07:54 UTC
